// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestingEFCoreBulkExtensions.Model;

#nullable disable

namespace TestingEFCoreBulkExtensions.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TestingEFCoreBulkExtensions.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bdc55e1b-800b-42d6-a00a-44e33ffe849d"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Tasty Cotton Chips"
                        },
                        new
                        {
                            Id = new Guid("f4cec862-c9f4-4dd4-8ce9-98bb115261cb"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Intelligent Steel Mouse"
                        },
                        new
                        {
                            Id = new Guid("31649ec5-35c7-4677-8d57-bda66b69504a"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Unbranded Wooden Keyboard"
                        },
                        new
                        {
                            Id = new Guid("c5bbe1d5-2b58-4921-bbf4-9f73909b563c"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Refined Metal Car"
                        },
                        new
                        {
                            Id = new Guid("36b77b17-7527-49d3-baea-455884d24ec7"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Tasty Plastic Chair"
                        },
                        new
                        {
                            Id = new Guid("af540569-9e52-471e-bfc2-ebd1bc621c3f"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Practical Fresh Gloves"
                        },
                        new
                        {
                            Id = new Guid("b8e3447e-f5e5-4277-8192-4d4018b96bd0"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Generic Cotton Keyboard"
                        },
                        new
                        {
                            Id = new Guid("c7dc399b-73c6-43e2-b16f-fd6e6f185fce"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Tasty Plastic Shirt"
                        },
                        new
                        {
                            Id = new Guid("d11d9836-7ce7-4e81-966b-8b8ebe3b3009"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handcrafted Granite Ball"
                        },
                        new
                        {
                            Id = new Guid("bf9b778d-568d-4783-8af2-570c32dee6b3"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Practical Plastic Table"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
